server:
  port: 8009
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/brocoli
    username: postgres
    password: 2408
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

security:
  jwt:
    secret: GamesFull123
    issuer: Main
    ttlMillis: 3600000